export const WORKOUT_LIST_REQUEST = "WORKOUT_LIST_REQUEST";
export const WORKOUT_LIST_SUCCESS = "WORKOUT_LIST_SUCCESS";
export const WORKOUT_LIST_FAIL = "WORKOUT_LIST_FAIL";

export const WORKOUT_DETAILS_REQUEST = "WORKOUT_DETAILS_REQUEST";
export const WORKOUT_DETAILS_SUCCESS = "WORKOUT_DETAILS_SUCCESS";
export const WORKOUT_DETAILS_FAIL = "WORKOUT_DETAILS_FAIL";
